name: Nix
on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-24.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  nix-fmt-check:
    needs: cancel-previous-runs
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix fmt -- --check ./

  nix-build:
    needs: cancel-previous-runs
    strategy:
      matrix:
        package: [tidal, tidal-link, tidal-parse]
        os: [ubuntu-24.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: install nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: clone project
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: build
        # https://github.com/NixOS/nix/issues/9530#issuecomment-2457467802
        run: nix build '.?submodules=1#default' --print-build-logs
